#
# Vivado (TM) v2016.1 (64-bit)
#
# build_prj.tcl: Tcl script for re-creating project 'CubeSat-FPGA-A7'
#
# Generated by Vivado on Sat Oct 14 08:36:34 -0500 2017
# IP Build 1537824 on Fri Apr  8 04:28:57 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build_prj.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/adc_interface.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/SD_Card_SPI_Byte_Transfer.vhd"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/SD_Card_SPI_baud_gen.vhd"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/ip_repo/fifo_tx/fifo_tx.xci"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/ip_repo/fifo_rx/fifo_rx.xci"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/ip_repo/fifo_preprocessing/fifo_preprocessing.xci"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/FC_intfc_SPI_Word_Transfer.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/ip_repo/fifo_processing/fifo_processing.xci"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/preprocessing_top.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/ip_repo/xadc_wiz_0/xadc_wiz_0.xci"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/timekeeper.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/SD_Card_SPI_controller.vhd"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/uart_tx.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/uart_rx.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/baud_generator.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/ip_repo/fifo_sd_card_write/fifo_sd_card_write.xci"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/FC_intfc_SPI_controller.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/processing_top.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/SD_Card_interface_top.vhd"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/device_temp.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/Detector_Top.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/Clock_Synchronization_Top.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/uart_top.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/memory_map.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/ip_repo/clk_mmcm_1/clk_mmcm_1.xci"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/FC_interface_top.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/FPGA_TOP.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/Data_Packetizer.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/adc_test_top.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/SD_Card_test_top.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/FC_intfc_command_decoder.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/uart_memory_map_test_top.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/shift_register.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/fifo_ram_interface.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/rtl/cd_conversion.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/ip_repo/fifo_1/fifo_1.xci"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/ip_repo/clk_wiz_0/clk_wiz_0.xci"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/ip_repo/fifo_sd_card_read/fifo_sd_card_read.xci"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/ip_repo/fc_fifo_tx/fc_fifo_tx.xci"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/constraints/constraints_top.xdc"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_fifo_test.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/testbench.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_uart_tx_test.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/tb_uart_tx_rx.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_uart_transmitter.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_uart_top_test.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_uart_rx_test.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_uart_receiver.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_SD_Card_Test.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_SD_Card_Spi_Slave.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_SD_Card_SPI_controller.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_SD_Card_Model_Top.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_SD_Card_Byte_Transfer.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_Detector_System_Test.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_adc_model.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_adc_interface_test.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/data_buffer_test.v"
#    "E:/HASP/Code/Current_Code/Curve_Fitting_Dev/FPGA-Code-CMOD-A7/sources/sim/TB_FPGA_Top.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "build_prj.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/CubeSat-FPGA-A7"]"

# Create project
create_project CubeSat-FPGA-A7 ./CubeSat-FPGA-A7 -part xc7a35tcpg236-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects CubeSat-FPGA-A7]
set_property "default_lib" "xil_defaultlib" $obj
set_property "part" "xc7a35tcpg236-1" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "xpm_libraries" "XPM_CDC XPM_MEMORY" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/sources/rtl/adc_interface.v"]"\
 "[file normalize "$origin_dir/sources/rtl/SD_Card_SPI_Byte_Transfer.vhd"]"\
 "[file normalize "$origin_dir/sources/rtl/SD_Card_SPI_baud_gen.vhd"]"\
 "[file normalize "$origin_dir/ip_repo/fifo_tx/fifo_tx.xci"]"\
 "[file normalize "$origin_dir/ip_repo/fifo_rx/fifo_rx.xci"]"\
 "[file normalize "$origin_dir/ip_repo/fifo_preprocessing/fifo_preprocessing.xci"]"\
 "[file normalize "$origin_dir/sources/rtl/FC_intfc_SPI_Word_Transfer.v"]"\
 "[file normalize "$origin_dir/ip_repo/fifo_processing/fifo_processing.xci"]"\
 "[file normalize "$origin_dir/sources/rtl/preprocessing_top.v"]"\
 "[file normalize "$origin_dir/ip_repo/xadc_wiz_0/xadc_wiz_0.xci"]"\
 "[file normalize "$origin_dir/sources/rtl/timekeeper.v"]"\
 "[file normalize "$origin_dir/sources/rtl/SD_Card_SPI_controller.vhd"]"\
 "[file normalize "$origin_dir/sources/rtl/uart_tx.v"]"\
 "[file normalize "$origin_dir/sources/rtl/uart_rx.v"]"\
 "[file normalize "$origin_dir/sources/rtl/baud_generator.v"]"\
 "[file normalize "$origin_dir/ip_repo/fifo_sd_card_write/fifo_sd_card_write.xci"]"\
 "[file normalize "$origin_dir/sources/rtl/FC_intfc_SPI_controller.v"]"\
 "[file normalize "$origin_dir/sources/rtl/processing_top.v"]"\
 "[file normalize "$origin_dir/sources/rtl/SD_Card_interface_top.vhd"]"\
 "[file normalize "$origin_dir/sources/rtl/device_temp.v"]"\
 "[file normalize "$origin_dir/sources/rtl/Detector_Top.v"]"\
 "[file normalize "$origin_dir/sources/rtl/Clock_Synchronization_Top.v"]"\
 "[file normalize "$origin_dir/sources/rtl/uart_top.v"]"\
 "[file normalize "$origin_dir/sources/rtl/memory_map.v"]"\
 "[file normalize "$origin_dir/ip_repo/clk_mmcm_1/clk_mmcm_1.xci"]"\
 "[file normalize "$origin_dir/sources/rtl/FC_interface_top.v"]"\
 "[file normalize "$origin_dir/sources/rtl/FPGA_TOP.v"]"\
 "[file normalize "$origin_dir/sources/rtl/Data_Packetizer.v"]"\
 "[file normalize "$origin_dir/sources/rtl/adc_test_top.v"]"\
 "[file normalize "$origin_dir/sources/rtl/SD_Card_test_top.v"]"\
 "[file normalize "$origin_dir/sources/rtl/FC_intfc_command_decoder.v"]"\
 "[file normalize "$origin_dir/sources/rtl/uart_memory_map_test_top.v"]"\
 "[file normalize "$origin_dir/sources/rtl/shift_register.v"]"\
 "[file normalize "$origin_dir/sources/rtl/fifo_ram_interface.v"]"\
 "[file normalize "$origin_dir/sources/rtl/cd_conversion.v"]"\
 "[file normalize "$origin_dir/ip_repo/fifo_1/fifo_1.xci"]"\
 "[file normalize "$origin_dir/ip_repo/clk_wiz_0/clk_wiz_0.xci"]"\
 "[file normalize "$origin_dir/ip_repo/fifo_sd_card_read/fifo_sd_card_read.xci"]"\
 "[file normalize "$origin_dir/ip_repo/fc_fifo_tx/fc_fifo_tx.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "rtl/SD_Card_SPI_Byte_Transfer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "rtl/SD_Card_SPI_baud_gen.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "rtl/SD_Card_SPI_controller.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "rtl/SD_Card_interface_top.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "FPGA_TOP" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/sources/constraints/constraints_top.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constraints/constraints_top.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/sources/sim/TB_fifo_test.v"]"\
 "[file normalize "$origin_dir/sources/sim/testbench.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_uart_tx_test.v"]"\
 "[file normalize "$origin_dir/sources/sim/tb_uart_tx_rx.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_uart_transmitter.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_uart_top_test.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_uart_rx_test.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_uart_receiver.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_SD_Card_Test.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_SD_Card_Spi_Slave.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_SD_Card_SPI_controller.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_SD_Card_Model_Top.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_SD_Card_Byte_Transfer.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_Detector_System_Test.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_adc_model.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_adc_interface_test.v"]"\
 "[file normalize "$origin_dir/sources/sim/data_buffer_test.v"]"\
 "[file normalize "$origin_dir/sources/sim/TB_FPGA_Top.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "TB_fifo_test" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7a35tcpg236-1 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7a35tcpg236-1" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7a35tcpg236-1 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7a35tcpg236-1" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:CubeSat-FPGA-A7"
