##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Sun Jun 11 17:42:55 2017
##  Generated by MIG Version 3.0
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A200T-SBG484
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         400 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K256M16XX-125
## Data Width: 16
## Time Period: 2500
## Data Mask: 1
##################################################################################################
############## NET - IOSTANDARD ##################


# PadFunction: IO_L10N_T1_D15_14 
set_property IOSTANDARD LVCMOS25 [get_ports {init_calib_complete}]
set_property PACKAGE_PIN AB22 [get_ports {init_calib_complete}]

# PadFunction: IO_L10P_T1_D14_14 
set_property IOSTANDARD LVCMOS25 [get_ports {tg_compare_error}]
set_property PACKAGE_PIN AB21 [get_ports {tg_compare_error}]


set_property INTERNAL_VREF  0.750 [get_iobanks 35]